# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory$character"

right_format = "$all"

[aws]
symbol = "  "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os.symbols]
Macos = " "

[package]
symbol = "󰏗 "

[php]
symbol = " "

[python]
symbol = " "

[swift]
symbol = " "
