# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = '$directory$character'

# move the rest of the prompt to the right
right_format = '$all'

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[aws]
symbol=' '
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[gcloud]
disabled = true

[directory]
read_only = ' 󰌾'
style = 'bg:peach fg:crust'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = '󰝚 '
'Pictures' = ' '
'Developer' = '󰲋 '

[docker_context]
symbol = ' '

[git_branch]
symbol = '󰊢 '

[git_commit]
tag_symbol = '  '

[golang]
symbol = ' '

[hostname]
ssh_symbol = ' '

[memory_usage]
symbol = '󰍛 '

[nodejs]
symbol = ' '

[os.symbols]
Macos = ' '

[package]
symbol = '󰏗 '

[php]
symbol = ' '

[python]
symbol = ' '

[swift]
symbol = ' '
